import React, { useState } from 'react';
import { FiFileText } from 'react-icons/fi';
import Button from '../components/ui/Button';
import Card from '../components/ui/Card';
import Modal from '../components/ui/Modal';

const HomePage: React.FC = () => {
  const [coverLetter, setCoverLetter] = useState('');
  const [showModal, setShowModal] = useState(false);

  const handleGenerateCoverLetter = async () => {
    const generatedLetter = "This is a placeholder for a generated cover letter. In a real scenario, this would be generated by an LLM based on the user's profile and the job description.";
    setCoverLetter(generatedLetter);
    setShowModal(true);
  };

  return (
    <>
      <Card className="p-6">
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-2xl font-bold text-gray-800">Dashboard</h2>
          <Button 
            onClick={handleGenerateCoverLetter} 
          >
            <FiFileText className="mr-2" />
            Generate Cover Letter
          </Button>
        </div>
        <p className="text-gray-600">
          Welcome to your Offer Hunter dashboard. Use the navigation on the left to manage your profile, view recommended jobs, and track your application history.
        </p>
      </Card>
      
      <Modal isOpen={showModal} onClose={() => setShowModal(false)} title="Generated Cover Letter">
        <div className="max-h-[60vh] overflow-y-auto pr-4">
            <p className="whitespace-pre-wrap text-gray-700">{coverLetter}</p>
        </div>
        <div className="flex justify-end mt-4">
            <Button onClick={() => setShowModal(false)} variant="secondary">
                Close
            </Button>
        </div>
      </Modal>
    </>
  );
};

export default HomePage;
