import React, { useState } from 'react';
import { FiCopy, FiCheck, FiChevronDown, FiFileText, FiGlobe, FiCode, FiMail } from 'react-icons/fi';

interface CopyOption {
  id: string;
  title: string;
  description: string;
  icon: React.ReactNode;
  format: string;
  metadata: boolean;
}

interface CopyOptionsProps {
  generatedAnswer: string;
  onCopy: (format: string, content: string) => Promise<boolean>;
  className?: string;
}

const CopyOptions: React.FC<CopyOptionsProps> = ({
  generatedAnswer,
  onCopy,
  className = ''
}) => {
  const [copied, setCopied] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);
  const [selectedFormat, setSelectedFormat] = useState('plain');

  const copyOptions: CopyOption[] = [
    {
      id: 'plain',
      title: 'Plain Text',
      description: 'Simple text format',
      icon: <FiFileText size={16} />,
      format: 'text/plain',
      metadata: false
    },
    {
      id: 'rich',
      title: 'Rich Text',
      description: 'Formatted for documents',
      icon: <FiGlobe size={16} />,
      format: 'text/html',
      metadata: true
    },
    {
      id: 'html',
      title: 'HTML',
      description: 'Web-ready format',
      icon: <FiCode size={16} />,
      format: 'text/html',
      metadata: false
    },
    {
      id: 'markdown',
      title: 'Markdown',
      description: 'Formatted for writing apps',
      icon: <FiCode size={16} />,
      format: 'text/markdown',
      metadata: true
    },
    {
      id: 'email',
      title: 'Email Format',
      description: 'Email and application ready',
      icon: <FiMail size={16} />,
      format: 'text/plain',
      metadata: true
    }
  ];

  const formatContent = (content: string, format: string): string => {
    const timestamp = new Date().toLocaleString();
    const metadata = `\n\n---\nGenerated by Offer Hunter Answer Generation\nTimestamp: ${timestamp}\nOriginal selection: ${window.location.href}`;

    switch (format) {
      case 'text/html':
        return `<div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">${content.replace(/\n/g, '<br>')}</div>`;
      
      case 'text/markdown':
        return content;
      
      case 'email':
        return `${content}${metadata}`;
      
      case 'rich':
        return content.replace(/\n/g, '<br>');
      
      default:
        return content;
    }
  };

  const handleCopy = async (formatId: string) => {
    const option = copyOptions.find(opt => opt.id === formatId);
    if (!option) return;

    const formattedContent = formatContent(generatedAnswer, option.format);
    const success = await onCopy(option.format, formattedContent);

    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      setIsExpanded(false);
    }
  };

  const selectedOption = copyOptions.find(opt => opt.id === selectedFormat);

  return (
    <div className={`copy-options ${className}`}>
      <div className="relative">
        {/* Main Copy Button */}
        <button
          onClick={() => handleCopy(selectedFormat)}
          disabled={!generatedAnswer}
          className={`
            w-full flex items-center justify-center gap-2 px-4 py-3 rounded-lg font-medium transition-all duration-200
            ${copied
              ? 'bg-green-600 text-white'
              : 'bg-blue-600 text-white hover:bg-blue-700'
            }
            disabled:bg-gray-400 disabled:cursor-not-allowed
          `}
        >
          {copied ? (
            <>
              <FiCheck size={16} />
              Copied!
            </>
          ) : (
            <>
              <FiCopy size={16} />
              Copy Answer
            </>
          )}
        </button>

        {/* Expand Button */}
        <button
          onClick={() => setIsExpanded(!isExpanded)}
          className="absolute right-2 top-1/2 transform -translate-y-1/2 p-1 hover:bg-blue-700 rounded transition-colors"
        >
          <FiChevronDown 
            size={16} 
            className={`text-white transition-transform duration-200 ${isExpanded ? 'rotate-180' : ''}`}
          />
        </button>
      </div>

      {/* Expanded Options */}
      {isExpanded && (
        <div className="mt-3 bg-white border rounded-lg shadow-lg p-3">
          <h4 className="text-sm font-medium text-gray-900 mb-3">
            Copy Options
          </h4>
          
          <div className="space-y-2">
            {copyOptions.map((option) => (
              <button
                key={option.id}
                onClick={() => handleCopy(option.id)}
                className={`
                  w-full flex items-center gap-3 p-2 rounded-lg border transition-all duration-200 text-left
                  ${selectedFormat === option.id
                    ? 'border-blue-500 bg-blue-50'
                    : 'border-gray-200 hover:border-gray-300 hover:bg-gray-50'
                  }
                `}
              >
                <div className={`
                  p-1.5 rounded-md
                  ${selectedFormat === option.id ? 'text-blue-600' : 'text-gray-500'}
                `}>
                  {option.icon}
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <span className={`
                      font-medium text-sm
                      ${selectedFormat === option.id ? 'text-blue-900' : 'text-gray-900'}
                    `}>
                      {option.title}
                    </span>
                    {option.metadata && (
                      <span className="px-1.5 py-0.5 bg-gray-100 text-gray-600 text-xs rounded">
                        +Metadata
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-gray-600">
                    {option.description}
                  </p>
                </div>
                <div className={`
                  w-3 h-3 rounded-full border
                  ${selectedFormat === option.id 
                    ? 'border-blue-500 bg-blue-500' 
                    : 'border-gray-300'
                  }
                `}>
                  {selectedFormat === option.id && (
                    <div className="w-1.5 h-1.5 bg-white rounded-full mx-auto mt-0.75" />
                  )}
                </div>
              </button>
            ))}
          </div>

          {/* Current Selection Indicator */}
          {selectedOption && (
            <div className="mt-3 pt-3 border-t border-gray-200">
              <div className="flex items-center gap-2 text-xs text-gray-600">
                <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                <span>
                  Selected: <strong className="text-gray-800">{selectedOption.title}</strong>
                </span>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Format Selector */}
      <div className="mt-2">
        <select
          value={selectedFormat}
          onChange={(e) => setSelectedFormat(e.target.value)}
          className="w-full px-3 py-1.5 text-xs border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
        >
          {copyOptions.map((option) => (
            <option key={option.id} value={option.id}>
              {option.title}
            </option>
          ))}
        </select>
      </div>
    </div>
  );
};

export default CopyOptions;